theme: jekyll-theme-cayman
title: SmmServer
description: Open source private server for Super Mario Maker (Wii U), integrated with SMMDB and Cemu
download: https://mega.nz/file/eUEWmTJb#RQc2mXc2mrmlIHCIFpEydadpnbsJa231pOixzQXDRe8